service: masters-pf-api # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

functions:
  RequestUnicorn:
    handler: handler.handler
    events:
      - http:
          path: masters-pf
          method: get
          cors: true